// prisma/seed-data/bios.ts

export const bios = [
  "Vivendo um dia de cada vez.",
  "Café, música e paz.",
  "Tentando manter a rotina em ordem.",
  "Amante de viagens e fotografia.",
  "Só quero viver tranquilo.",
  "Filmes, séries e finais de semana.",
  "Criando memórias pelo caminho.",
  "Sempre ouvindo alguma playlist.",
  "Entre trabalho e descanso.",
  "Apaixonado por dias chuvosos.",
  "Sorrindo apesar da correria.",
  "Apreciando os pequenos momentos.",
  "Viciado em café gelado.",
  "Tentando ser minha melhor versão.",
  "Colecionando experiências.",
  "Energia boa apenas.",
  "Dormir resolve quase tudo.",
  "Vivendo fora do modo automático.",
  "Mais praia, menos estresse.",
  "A vida acontece nos detalhes.",
  "Música alta e mente leve.",
  "Aprendendo constantemente.",
  "Sem pressa para viver.",
  "Só mais um sonhador comum.",
  "Apreciador de boas conversas.",
  "Criando minha própria história.",
  "Dias simples são os melhores.",
  "Vivendo entre memes e boletos.",
  "Nem online eu sei o que tô fazendo.",
  "Tentando equilibrar tudo.",
  "Fotos aleatórias e pensamentos soltos.",
  "Mais leveza, menos cobrança.",
  "A vida não precisa ser perfeita.",
  "Sempre buscando paz mental.",
  "Apaixonado por pôr do sol.",
  "Colecionando momentos felizes.",
  "Sobrevivendo à semana.",
  "Um café e tudo melhora.",
  "Vivendo intensamente os detalhes.",
  "Modo economia de energia ativado.",
  "Sorriso cansado porém sincero.",
  "Mente tranquila, coração leve.",
  "Nem tudo precisa fazer sentido.",
  "Vivendo no meu próprio ritmo.",
  "Tentando desacelerar.",
  "Pequenos passos ainda são progresso.",
  "Apenas seguindo em frente.",
  "Viver já ocupa bastante tempo.",
  "Dias bons também chegam.",
  "Mais silêncio, menos confusão.",
  "Fugindo da correria sempre que dá.",
  "Tentando não surtar diariamente.",
  "Rotina corrida e sonhos grandes.",
  "Uma bagunça organizada.",
  "A vida passa rápido demais.",
  "Aproveitando o agora.",
  "Todo mundo cansado ultimamente.",
  "Respirando fundo e seguindo.",
  "Apenas existindo.",
  "Caos interno com aparência calma.",
  "Meu lugar favorito é minha cama.",
  "Tentando voltar a ler mais.",
  "Vivendo no modo aleatório.",
  "Mais momentos offline.",
  "Sem energia social hoje.",
  "Apreciando o silêncio.",
  "Focado em melhorar aos poucos.",
  "Tudo passa eventualmente.",
  "Dias tranquilos são raros.",
  "A vida acontece muito rápido.",
  "Aprendendo a desacelerar.",
  "Paz mental virou prioridade.",
  "Só tentando manter a sanidade.",
  "Fases boas também chegam.",
  "Cuidando mais de mim.",
  "O básico bem feito já basta.",
  "Apenas alguém comum.",
  "Sumi mas tô vivo.",
  "Vontade de viajar sem voltar.",
  "Dormir é meu hobby favorito.",
  "Tentando manter a positividade.",
  "Entre o caos e a calmaria.",
  "Sem expectativas irreais.",
  "Vivendo minha própria timeline.",
  "Dias melhores virão.",
  "Às vezes só quero silêncio.",
  "Tentando aproveitar mais o presente.",
  "Nada muito planejado.",
  "A vida adulta é cansativa.",
  "Vivendo um reboot pessoal.",
  "Fazendo o possível todos os dias.",
  "Tudo no seu tempo.",
  "Mais autenticidade sempre.",
  "Vivendo sem filtro.",
  "Apenas tentando ficar bem.",
  "Ainda descobrindo muita coisa.",
  "Pessoas cansadas se reconhecem.",
  "Dias leves são especiais.",
  "Menos ansiedade, mais vida.",
  "Sobrevivendo à rotina.",
  "Sigo tentando.",
  "Um passo por vez.",
];