// prisma/seed-data/posts.ts

export const posts = [
  "Hoje o dia passou voando.",
  "Preciso urgentemente organizar minha rotina.",
  "Nada melhor que um banho depois de um dia cansativo.",
  "O café de hoje salvou meu humor.",
  "Queria que finais de semana durassem mais.",
  "Mais alguém completamente sem energia hoje?",
  "Acordar cedo deveria ser opcional.",
  "Dia corrido mas produtivo.",
  "Apenas tentando sobreviver à semana.",
  "Escutando música e ignorando problemas.",
  "Às vezes tudo que a gente precisa é descansar.",
  "Finalmente consegui colocar algumas coisas em ordem.",
  "O tempo tá passando rápido demais.",
  "Queria desligar a mente por algumas horas.",
  "Pequenas conquistas também merecem comemoração.",
  "Hoje foi um daqueles dias longos.",
  "Só queria estar em uma praia agora.",
  "Nada supera uma boa noite de sono.",
  "A vida adulta realmente é cansativa.",
  "Preciso parar de procrastinar.",
  "Dia perfeito pra ficar em casa.",
  "Mais alguém sentindo o ano passar rápido?",
  "Queria voltar a dormir sem preocupações.",
  "Tô precisando de férias urgentemente.",
  "O dia mal começou e eu já tô cansado.",
  "Às vezes sumir um pouco faz bem.",
  "Hoje eu só quero paz.",
  "Tentando manter a cabeça no lugar.",
  "Tudo parece mais difícil quando a gente tá cansado.",
  "Aproveitando os pequenos momentos.",
  "Hoje foi dia de colocar a vida em ordem.",
  "Nem todo dia precisa ser produtivo.",
  "Só queria dormir sem despertador amanhã.",
  "A playlist certa melhora qualquer dia.",
  "Queria aprender a desacelerar.",
  "Dias tranquilos são raros ultimamente.",
  "Apenas vivendo no automático hoje.",
  "Nada melhor que comida boa e silêncio.",
  "A rotina consome muita energia.",
  "Hoje eu fiquei mais offline.",
  "Tô tentando melhorar aos poucos.",
  "O descanso também é importante.",
  "Nem tudo precisa ser resolvido agora.",
  "Queria conseguir manter hábitos saudáveis.",
  "Hoje o cansaço venceu.",
  "A vida fica mais leve quando a mente desacelera.",
  "Passei o dia inteiro adiando tarefas.",
  "Tem dias que tudo parece pesado.",
  "Apenas mais um dia comum.",
  "O silêncio faz bem às vezes.",
  "Preciso voltar a cuidar mais de mim.",
  "Hoje foi um bom dia apesar da correria.",
  "A ansiedade consome energia demais.",
  "Café e música resolveram metade dos problemas.",
  "Tô tentando aproveitar mais o presente.",
  "Hoje eu só queria ficar quieto.",
  "Dias melhores sempre chegam.",
  "A vida anda muito acelerada.",
  "Ficar offline um pouco ajuda bastante.",
  "Dormir cedo virou meta impossível.",
  "Mais alguém cansado sem motivo?",
  "Hoje eu consegui descansar um pouco.",
  "Tentando colocar a mente em paz.",
  "A semana ainda nem terminou.",
  "Nada mais valioso que paz mental.",
  "Aproveitando o clima tranquilo de hoje.",
  "Precisando renovar as energias.",
  "Hoje foi dia de resolver pendências.",
  "Só queria menos preocupação.",
  "Um dia de cada vez.",
  "A vida não vem com manual mesmo.",
  "Às vezes a gente só precisa respirar fundo.",
  "Hoje eu desacelerei um pouco.",
  "Nem sempre a gente consegue dar conta de tudo.",
  "Dias leves fazem diferença.",
  "Tô precisando me desconectar um pouco.",
  "Hoje foi produtivo até demais.",
  "Mais alguém querendo sumir por uma semana?",
  "Finalmente consegui descansar.",
  "A cabeça não para um segundo.",
  "Queria entender melhor minha própria rotina.",
  "O melhor momento do dia é chegar em casa.",
  "Hoje eu fiquei longe do celular por algumas horas.",
  "Pequenos descansos ajudam muito.",
  "A vida adulta veio sem tutorial.",
  "Tentando não me cobrar tanto.",
  "Hoje eu só queria silêncio.",
  "Tudo passa eventualmente.",
  "Dias corridos demais ultimamente.",
  "O tempo livre anda raro.",
  "Apenas seguindo em frente.",
  "Amanhã eu tento de novo.",
  "Hoje foi um daqueles dias estranhos.",
  "A mente cansada pesa muito.",
  "Preciso urgentemente dormir melhor.",
  "Nada melhor que ficar em paz consigo mesmo.",
  "A rotina às vezes sufoca.",
  "Queria viajar sem data pra voltar.",
  "Mais um dia vencido.",
  "Tentando encontrar equilíbrio.",
  "O importante é continuar.",
  "Hoje eu consegui respirar um pouco.",
];